# index:
#    path: /
#    controller: App\Controller\DefaultController::index

# home: 
#     path: /home
#     controller: App\Controller\HomeController::index

# contact:
#     path: /contact
#     controller: App\Controller\HomeController::contact